version: '3'
services:

    # The Application
    app:
        build:
            context: ./
            args:
                - ENABLE_XDEBUG=${ENABLE_XDEBUG}
            dockerfile: app.dockerfile
        working_dir: /var/www
        volumes:
            - "../:/var/www"
            - ./app.ini:/usr/local/etc/php/conf.d/app.ini
        links:
            - dbserver
        environment:
            PHP_EXTENSION_XDEBUG: 1
        extra_hosts: # <-- does no harm
            - "host.docker.internal:host-gateway" # <-- does no harm

        # The Web Server
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes:
            - "../:/var/www"
            - ./app.ini:/usr/local/etc/php/conf.d/app.ini
        depends_on:
            - app
        ports:
            - ${WEB_PORT:-80}:80
        extra_hosts: # <--- this is required
            - "host.docker.internal:host-gateway" # <--- this is required
    dbserver:
        image: mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password  --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --sql-mode=NO_ENGINE_SUBSTITUTION --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        ports: 
            - ${MYSQL_PORT:-3306}:3306
        hostname: dbserver
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-laravel}
            # MYSQL_USER: ${MYSQL_USER:-root}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
        volumes:
            - ../db_data:/var/lib/mysql
    phpmyadmin:
        build:
            context: ./
            dockerfile: phpmyadmin.dockerfile
        # image: phpmyadmin/phpmyadmin:4.7
        depends_on: 
            - dbserver
        ports:
            - ${PMA_PORT:-81}:80
        environment:
            PMA_ARBITRARY: 0
            PMA_HOST: dbserver
            MYSQL_USER: ${MYSQL_USER:-root}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
